name: Publish
on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    # optional but recommended for additional protections
    environment: pypi
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install build commitizen

      - name: Build distribution
        run: python -m build

      - name: Generate release notes with Commitizen
        run: |
          set -euo pipefail
          cz changelog --dry-run "${GITHUB_REF_NAME}" > release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          body_path: release_notes.md

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
